// mockCities.ts

// Define the type for city objects
export type City = {
    city: string;
    country: string;
  };
  
  // Simulate API call or replace with a real one
// Simulate API call or replace with a real one
export const mockCities: City[] = [
    { city: "New York", country: "US" },
    { city: "Los Angeles", country: "US" },
    { city: "Tokyo", country: "JP" },
    { city: "London", country: "GB" },
    { city: "Paris", country: "FR" },
    { city: "Berlin", country: "DE" },
    { city: "Sydney", country: "AU" },
    { city: "Toronto", country: "CA" },
    { city: "Moscow", country: "RU" },
    { city: "Dubai", country: "AE" },
    { city: "Rio de Janeiro", country: "BR" },
    { city: "Cape Town", country: "ZA" },
    { city: "Beijing", country: "CN" },
    { city: "Cairo", country: "EG" },
    { city: "Bangkok", country: "TH" },
    { city: "Tunis", country: "TN" },
    { city: "Madrid", country: "ES" },
    { city: "Rome", country: "IT" },
    { city: "Istanbul", country: "TR" },
    { city: "Mumbai", country: "IN" },
    { city: "Seoul", country: "KR" },
    { city: "Mexico City", country: "MX" },
    { city: "Buenos Aires", country: "AR" },
    { city: "Athens", country: "GR" },
    { city: "Lima", country: "PE" },
    { city: "Santiago", country: "CL" },
    { city: "Kuala Lumpur", country: "MY" },
    { city: "Singapore", country: "SG" },
    { city: "Hanoi", country: "VN" },
    { city: "Nairobi", country: "KE" },
    { city: "Lisbon", country: "PT" },
    { city: "Stockholm", country: "SE" },
    { city: "Oslo", country: "NO" },
    { city: "Zurich", country: "CH" },
    { city: "Brussels", country: "BE" },
    { city: "Vienna", country: "AT" },
    { city: "Dublin", country: "IE" },
    { city: "Helsinki", country: "FI" },
    { city: "Riyadh", country: "SA" },
    { city: "Amsterdam", country: "NL" },
    { city: "Bangalore", country: "IN" },
    { city: "Jakarta", country: "ID" },
    { city: "Kiev", country: "UA" },
    { city: "Caracas", country: "VE" },
    { city: "Lagos", country: "NG" },
    { city: "Manila", country: "PH" },
    { city: "Montreal", country: "CA" },
    { city: "Addis Ababa", country: "ET" },
    { city: "Helsinki", country: "FI" },
    { city: "Copenhagen", country: "DK" },
    { city: "Budapest", country: "HU" },
    { city: "Copenhagen", country: "DK" },
    { city: "Helsinki", country: "FI" },
    { city: "Brisbane", country: "AU" },
    { city: "Algiers", country: "DZ" },
    { city: "Doha", country: "QA" },
    { city: "Tbilisi", country: "GE" },
    { city: "Tashkent", country: "UZ" },
    { city: "Abu Dhabi", country: "AE" },
    { city: "Lisbon", country: "PT" },
    { city: "Muscat", country: "OM" },
    { city: "Belgrade", country: "RS" },
    { city: "Riga", country: "LV" },
    { city: "Sofia", country: "BG" },
    { city: "Sarajevo", country: "BA" },
    { city: "Yerevan", country: "AM" },
    { city: "Porto", country: "PT" },
    { city: "Baku", country: "AZ" },
    { city: "Nassau", country: "BS" },
    { city: "Nairobi", country: "KE" },
    { city: "Montevideo", country: "UY" },
    { city: "Asunción", country: "PY" },
    { city: "Tegucigalpa", country: "HN" },
    { city: "Quito", country: "EC" },
    { city: "San Salvador", country: "SV" },
    { city: "Havana", country: "CU" },
  ];
      